data = ['INSERT INTO quiz VALUES (1, "All countries in the world", "Name all 194 independet countries in the world.", "mapquiz", "select name from country where independent = true")',
        'INSERT INTO quiz VALUES (2, "All countries in Europe", "Name all 45 independet countries in Europe.", "mapquiz", \'select name from country where independent = true and continent = "Europe"\')',
        'INSERT INTO quiz VALUES (3, "All countries in Asia", "Name all 45 independet countries in Asia.", "mapquiz", \'select name from country where independent = true and continent = "Asia"\')',
        'INSERT INTO quiz VALUES (4, "All countries in North America", "Name all 23 independet countries in North America.", "mapquiz", \'select name from country where independent = true and continent = "North America"\')',
        'INSERT INTO quiz VALUES (5, "All countries in South America", "Name all 12 independet countries in South America.", "mapquiz", \'select name from country where independent = true and continent = "South America"\')',
        'INSERT INTO quiz VALUES (6, "All countries in Africa", "Name all 54 independet countries in Africa.", "mapquiz", \'select name from country where independent = true and continent = "Africa"\')',
        'INSERT INTO quiz VALUES (7, "All countries in Oceania", "Name all 15 independet countries in Oceania.", "mapquiz", \'select name from country where independent = true and continent = "Oceania"\')',
        'INSERT INTO quiz VALUES (8, "All flags of the world", "Name the flag of all 194 independet countries in the world.", "flagquiz", "select name from country where independent = true")',
        'INSERT INTO quiz VALUES (9, "All flags of Europe", "Name the flag of all 45 independet countries in Europe.", "flagquiz", \'select name from country where independent = true and continent = "Europe"\')',
        'INSERT INTO quiz VALUES (10, "All flags of Asia", "Name the flag of all 45 independet countries in Asia.", "flagquiz", \'select name from country where independent = true and continent = "Asia"\')',
        'INSERT INTO quiz VALUES (11, "All flags of North America", "Name the flag of all 23 independet countries in North America.", "flagquiz", \'select name from country where independent = true and continent = "North America"\')',
        'INSERT INTO quiz VALUES (12, "All flags of South America", "Name the flag of all 12 independet countries in South America.", "flagquiz", \'select name from country where independent = true and continent = "South America"\')',
        'INSERT INTO quiz VALUES (13, "All flags of in Africa", "Name the flag of all 54 independet countries in Africa.", "flagquiz", \'select name from country where independent = true and continent = "Africa"\')',
        'INSERT INTO quiz VALUES (14, "All flags of in Oceania", "Name the flag of all 15 independet countries in Oceania.", "flagquiz", \'select name from country where independent = true and continent = "Oceania"\')']

#Name the flag of all 15 independent countries in Oceania